src/Entity/Client.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormTypeInterface;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
#[ApiResource]
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="bigint")
     */
    private $Code_postal;

    /**
     * @ORM\OneToMany(targetEntity=LivretHeure::class, mappedBy="id_client")
     */
    private $livretHeures;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $actif;

    public function __construct()
    {
        $this->livretHeures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdClient(): ?string
    {
        return $this->id_client;
    }

    public function setIdClient(string $id_client): self
    {
        $this->id_client = $id_client;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->Code_postal;
    }

    public function setCodePostal(string $Code_postal): self
    {
        $this->Code_postal = $Code_postal;

        return $this;
    }

    /**
     * @return Collection|LivretHeure[]
     */
    public function getLivretHeures(): Collection
    {
        return $this->livretHeures;
    }

    public function addLivretHeure(LivretHeure $livretHeure): self
    {
        if (!$this->livretHeures->contains($livretHeure)) {
            $this->livretHeures[] = $livretHeure;
            $livretHeure->setIdClient($this);
        }

        return $this;
    }

    public function removeLivretHeure(LivretHeure $livretHeure): self
    {
        if ($this->livretHeures->removeElement($livretHeure)) {
            // set the owning side to null (unless already changed)
            if ($livretHeure->getIdClient() === $this) {
                $livretHeure->setIdClient(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nom ;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(?bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Repository\UserApiRepository;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"userid"}, message="Un utilisateur existe déjà avec cette userid")
 * @UniqueEntity(fields={"username"}, message="Un utilisateur existe déjà avec cette username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $userid;

    /**
     * @ORM\OneToMany(targetEntity=LivretHeure::class, mappedBy="user_id")
     */
    private $livretHeures;

    /**
     * @ORM\OneToMany(targetEntity=Essence::class, mappedBy="user")
     */
    private $essences;

    /**
     * @ORM\OneToMany(targetEntity=EssenceGNR::class, mappedBy="user")
     */
    private $essenceGNRs;


    public function __construct()
    {
        $this->livretHeures = new ArrayCollection();
        $this->essences = new ArrayCollection();
        $this->essenceGNRs = new ArrayCollection();
    }


    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }



    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserid(): ?string
    {
        return $this->userid;
    }

    public function setUserid(?string $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

//////////////////////////////////////////////

    public function addRoles(string $roles): self
    {
        if (!in_array($roles, $this->roles)) {
            $this->roles[] = $roles;
        }

        return $this;
    }



    public function hasRoles(string $roles): bool
    {
        return in_array($roles, $this->roles);
    }

    /**
     * @return Collection|LivretHeure[]
     */
    public function getLivretHeures(): Collection
    {
        return $this->livretHeures;
    }

    public function addLivretHeure(LivretHeure $livretHeure): self
    {
        if (!$this->livretHeures->contains($livretHeure)) {
            $this->livretHeures[] = $livretHeure;
            $livretHeure->setUserId($this);
        }

        return $this;
    }

    public function removeLivretHeure(LivretHeure $livretHeure): self
    {
        if ($this->livretHeures->removeElement($livretHeure)) {
            // set the owning side to null (unless already changed)
            if ($livretHeure->getUserId() === $this) {
                $livretHeure->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Essence[]
     */
    public function getEssences(): Collection
    {
        return $this->essences;
    }

    public function addEssence(Essence $essence): self
    {
        if (!$this->essences->contains($essence)) {
            $this->essences[] = $essence;
            $essence->setUser($this);
        }

        return $this;
    }

    public function removeEssence(Essence $essence): self
    {
        if ($this->essences->removeElement($essence)) {
            // set the owning side to null (unless already changed)
            if ($essence->getUser() === $this) {
                $essence->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->username;
    }

    /**
     * @return Collection|EssenceGNR[]
     */
    public function getEssenceGNRs(): Collection
    {
        return $this->essenceGNRs;
    }

    public function addEssenceGNR(EssenceGNR $essenceGNR): self
    {
        if (!$this->essenceGNRs->contains($essenceGNR)) {
            $this->essenceGNRs[] = $essenceGNR;
            $essenceGNR->setUser($this);
        }

        return $this;
    }

    public function removeEssenceGNR(EssenceGNR $essenceGNR): self
    {
        if ($this->essenceGNRs->removeElement($essenceGNR)) {
            // set the owning side to null (unless already changed)
            if ($essenceGNR->getUser() === $this) {
                $essenceGNR->setUser(null);
            }
        }

        return $this;
    }


}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{

    /**
     * @Route("/useradd", name="user")
     */
    public function index ()
    {
        $user = new User();
        $user->setUsername('nomUtilisateur');
        $user->setUserid('nur');
        $user->setPassword('passwordenclair');

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();


        return $this->render('...',
        [
            'controller_name'=>'UserController',
        ]);
    }


}

templates/user/affiche.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion essence{% endblock %}
{% block content %}
    <div class="container-fluid p-4 ">
        <div class="row">
            <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 color">
                {% for flashError in app.flashes('verify_email_error') %}
                    <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                {% endfor %}
                <h1 class="h3 mb-3 font-weight-normal">affiche de l'essence</h1>


                <table>
                    <thead>
                    <tr>
                        <th colspan="2">The table header</th>
                    </tr>
                    </thead>
                    <tbody>



                        {% for dernierEssence in dernierEssences %}
                            <tr>
                                <td>{{ dernierEssence.date }}</td>
                                <td>{{ dernierEssence.user }}</td>
                                <td>{{ dernierEssence.vehicule }}</td>
                                <td>{{ dernierEssence.volume }}</td>
                                <td><a href="#">lien</a></td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>



            </div>
        </div>
    </div>

{% endblock %}

templates/user/affichePlan.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion essence{% endblock %}
{% block content %}
    <div class="container-fluid p-4">
        <div class="row">
            <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4 color">
                {% for flashError in app.flashes('verify_email_error') %}
                    <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                {% endfor %}
                <h1 class="h3 mb-3 font-weight-normal">Plan</h1>

                <table>
                    <thead>
                    <tr>
                        <th colspan="2">Vos dernières entré</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dernierEssence in dernierEssences %}
                        <tr>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/calendar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('home') }}">Create new booking</a>

    <div id="calendar-holder"></div>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css">
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', () => {
            var calendarEl = document.getElementById('calendar-holder');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                defaultView: 'dayGridMonth',
                editable: true,
                eventSources: [
                    {
                        url: "{{ path('fc_load_events') }}",
                        method: "POST",
                        extraParams: {
                            filters: JSON.stringify({})
                        },
                        failure: () => {
                            // alert("There was an error while fetching FullCalendar!");
                        },
                    },
                ],
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay',
                },
                plugins: [ 'interaction', 'dayGrid', 'timeGrid' ], // https://fullcalendar.io/docs/plugin-index
                timeZone: 'UTC',
            });
            calendar.render();
        });
    </script>
{% endblock %}

templates/user/heureModif.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gestion essence{% endblock %}
{% block content %}
    <div class="container-fluid  p-4 mb-4">
        <div class="row">
            <div class="col-sm-12 col-md-8 offset-md-2 col-lg-8 offset-lg-2 color  mb-4 p-4">
                {% for flashError in app.flashes('verify_email_error') %}
                    <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                {% endfor %}
                <h1 class="h3 mb-3 font-weight-normal">Modification de la saisie</h1>


                {{ form_start(registrationForm) }}
                <div class="form-group" >
                    {{ form_label(registrationForm.user_id, 'Nom d\'utilisateur') }}
                    {{ form_widget(registrationForm.user_id, {'attr': {'class': 'form-control' }}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.user_id) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.date, 'Date') }}
                    {{ form_widget(registrationForm.date, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.date) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.id_client, 'id_client') }}
                    {{ form_widget(registrationForm.id_client, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.id_client) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.nbre_heure, 'nbre_heure') }}
                    {{ form_widget(registrationForm.nbre_heure, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.nbre_heure) }}</small>
                </div>
                {#<div class="form-group">
                    {{ form_label(registrationForm.ville, 'ville') }}
                    {{ form_widget(registrationForm.ville, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.ville) }}</small>
                </div>#}
                <div class="form-group">
                    {{ form_label(registrationForm.abs_maladie, 'abs_maladie') }}
                    {{ form_widget(registrationForm.abs_maladie, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.abs_maladie) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.CP, 'CP') }}
                    {{ form_widget(registrationForm.CP, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.CP) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.formation, 'Formation') }}
                    {{ form_widget(registrationForm.formation, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.formation) }}</small>
                </div>
                <button type="submit"  class="btn" style="background-color: rgba(127, 0, 0, 0.5); color: white" onclick="if (confirm('Es-tu certain de vouloir AJOUTER cette donnée?')) commentDelete(1); return false">Envoie des données</button>
                <input type = "button" value = "Retour"  class="btn" style="background-color: rgba(127, 0, 0, 0.5); color: white" onclick = "history.back()">
                {{ form_end(registrationForm) }}





            </div>
        </div>
    </div>

{% endblock %}

templates/user/heureOLD.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', () => {
            var calendarEl = document.getElementById('calendar-holder');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                defaultView: 'dayGridMonth',
                editable: true,
                eventSources: [
                    {
                        url: "{{ path('fc_load_events') }}",
                        method: "POST",
                        extraParams: {
                            filters: JSON.stringify({})
                        },
                        failure: () => {
                            // alert("There was an error while fetching FullCalendar!");
                        },
                    },
                ],
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay',
                },
                plugins: [ 'interaction', 'dayGrid', 'timeGrid' ], // https://fullcalendar.io/docs/plugin-index
                timeZone: 'UTC',
            });
            calendar.render();
        });
    </script>
{% endblock %}





{% block title %}Gestion essence{% endblock %}
{% block content %}
    <div class="container p-4 color">
        <div class="row">
            <div class="col-sm-12 col-md-6 offset-md-3 col-lg-4 offset-lg-4">
                {% for flashError in app.flashes('verify_email_error') %}
                    <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                {% endfor %}
                <h1 class="h3 mb-3 font-weight-normal">Gestion de l'essence</h1>


                {{ form_start(registrationForm) }}
                <div class="form-group" >
                    {{ form_label(registrationForm.user_id, 'Nom d\'utilisateur') }}
                    {{ form_widget(registrationForm.user_id, {'attr': {'class': 'form-control' }}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.user_id) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.date, 'Date') }}
                    {{ form_widget(registrationForm.date, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.date) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.id_client, 'id_client') }}
                    {{ form_widget(registrationForm.id_client, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.id_client) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.nbre_heure, 'nbre_heure') }}
                    {{ form_widget(registrationForm.nbre_heure, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.nbre_heure) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.ville, 'ville') }}
                    {{ form_widget(registrationForm.ville, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.ville) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.abs_maladie, 'abs_maladie') }}
                    {{ form_widget(registrationForm.abs_maladie, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.abs_maladie) }}</small>
                </div>
                <div class="form-group">
                    {{ form_label(registrationForm.CP, 'CP') }}
                    {{ form_widget(registrationForm.CP, {'attr': {'class': 'form-control'}}) }}
                    <small class="text-danger">{{ form_errors(registrationForm.CP) }}</small>
                </div>
                <button type="submit"  class="btn">Envoie des données</button>
                {{ form_end(registrationForm) }}


                <table>
                    <thead>
                    <tr>
                        <th colspan="2">Vos dernières entré</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dernierEssence in dernierEssences %}
                        <tr>
                            <td>{{ dernierEssence.date|date('d/m/Y') }}</td>
                            <td>{{ dernierEssence.getUserId }}</td>
                            <td>{{ dernierEssence.getIdClient }}</td>
                            <td>{{ dernierEssence.getNbreHeure }}</td>
                            <td>{{ dernierEssence.getVille }}</td>
                            <td>{{ dernierEssence.getAbsMaladie }}</td>
                            <td>{{ dernierEssence.getCP }}</td>
                            <td><a href="{{ path('heureModif', {'id':dernierEssence.id}) }}">modifier</a></td>
                            <td>
                                <a href="{{ path('suppHeure', {'id':dernierEssence.id}) }}" class="text-danger" onclick="confirm('Es-tu certain de vouloir supprimer cet utilisateur?')">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="18">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
                                    </svg>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                
                {#
                time can be any string acceptable by http://www.php.net/strtotime, the
                template will output that time's month.
                If you don't want to pass in a date you can set time like this:
                {% set time = "now"|date("U") %}
                {% set time = "December 2012"|date("U") %}
                How ever you want to output items onto the calendar is a different issue,
                but I'd assume pushing everything into an array numerically indexed by that day:
                $days = array(1=>array('Something on the first'),31=>array('Halloween'));
                #}
                {% set time = "now"|date("U") %}
                <table>
                    <thead>
                    <tr>
                        <th colspan="7" class="center">
                            {{ time|date('F') }}
                        </th>
                    </tr>
                    <tr>
                        <th width="15%">Lundi</th>
                        <th width="15%">Mardi</th>
                        <th width="16%">Mercredi</th>
                        <th width="15%">Jeudi</th>
                        <th width="15%">Vedredi</th>
                        <th width="12%">Samedi</th>
                        <th width="12%">Dimanche</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        {% set daysInMonth = time|date('t') %}
                        {% set startDow = time|date('F 1\\s\\t Y')|date('N') - 1 %}
                        {% set dow = startDow %}
                        {% for day in range(1,daysInMonth) %}
                        {% if loop.first and startDow != 0 %}
                            <td colspan="{{ startDow }}"></td>
                        {% endif %}
                        <td>
                            <div>
                                <div>{{ day }}</div>
                                <div>
                                    {# ////////////////////////////////////////////////////////////// #}

                                    {% if startDow == startDow  %}

                                        <a href='#'>{{ time|date() }}</a>


                                        {#<tr>
                                            <td>{{ dernierEssence.date|date('d/m/Y') }}</td>
                                            <td>{{ dernierEssence.getUserId }}</td>
                                            <td>{{ dernierEssence.getIdClient }}</td>
                                            <td>{{ dernierEssence.getNbreHeure }}</td>
                                            <td>{{ dernierEssence.getVille }}</td>
                                            <td>{{ dernierEssence.getAbsMaladie }}</td>
                                            <td>{{ dernierEssence.getCP }}</td>
                                            <td><a href="{{ path('heureModif', {'id':dernierEssence.id}) }}">modifier</a></td>
                                            <td>
                                                <a href="{{ path('suppHeure', {'id':dernierEssence.id}) }}" class="text-danger" onclick="confirm('Es-tu certain de vouloir supprimer cet utilisateur?')">
                                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" width="18">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
                                                    </svg>
                                                </a>
                                            </td>
                                        </tr>
                                        {% endfor %}#}
                                    {% endif %}

                                    {# ////////////////////////////////////////////////////////////// #}
                                    {# day content here #}
                                </div>
                            </div>
                        </td>
                        {% if loop.last and dow != 6 %}
                            <td colspan="{{ 6 - dow }}">&nbsp;</td>
                        {% endif %}
                        {% if dow == 6 %}
                        {% set dow = 0 %}
                    </tr>
                    <tr>
                        {% else %}
                            {% set dow = dow + 1 %}
                        {% endif %}
                        {% endfor %}
                    </tr>
                    </tbody>
                </table>









            </div>
        </div>
    </div>
{% endblock %}